AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3UploaderDemo

  Sample SAM Template for S3UploaderDemo
  
Parameters:
  S3BucketName:
    Type: String
    Default: s3-upload-demo-s3-bucket
  DynamoDBTableName:
    Type: String
    Default: s3-upload-demo-dynamo-table

Globals:
  Api:
    BinaryMediaTypes:
    - "image~1*"
  Function:
    Timeout: 60
    Environment:
      Variables:
        S3_BUCKET: !Ref S3BucketName
        DYNAMODB_TABLE: !Ref DynamoDBTableName

Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: postS3.handler
      Runtime: nodejs10.x
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:PutObject
            Resource:
              Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3BucketName
                - "/*"
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            Resource: !GetAtt DynamoDB.Arn
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post

  DequeueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dequeue.handler
      Runtime: nodejs10.x
      Events:
        ProcessStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDB.StreamArn
            StartingPosition: LATEST

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  UploadApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
  S3Bucket:
    Value: !Ref S3Bucket
